In [76]:
#Import libraries
import pandas as pd
import numpy as np

Question 1: Version of Pandas

In [2]:
pd.__version__

'2.1.0'

In [78]:
#Reading the dataset housing.csv
df = pd.read_csv('housing.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [82]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

Question 2: Number of columns in the dataset

In [79]:
df.shape

(20640, 10)

Question 3: Select columns with missing data

In [10]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [11]:
df.isnull().any()

longitude             False
latitude              False
housing_median_age    False
total_rooms           False
total_bedrooms         True
population            False
households            False
median_income         False
median_house_value    False
ocean_proximity       False
dtype: bool

Question 4: Number of unique values in the 'ocean_proximity' column

In [80]:
df.ocean_proximity.nunique()

5

In [81]:
df.ocean_proximity.unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

Question 5: Average value of the 'median_house_value' for the houses near the bay

In [83]:
df.loc[df['ocean_proximity'] == 'NEAR BAY', ['median_house_value']].mean()

median_house_value    259212.31179
dtype: float64

Question 6: Has the mean value changed after filling missing values?

In [85]:
# 1. Calculate the average of total_bedrooms column in the dataset.
mean_value = df['total_bedrooms'].mean().round(3)
print(mean_value)

537.871


In [87]:
# 2. Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
df['total_bedrooms'] = df['total_bedrooms'].fillna(value = mean_value)


In [92]:
# Checking if any null values
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [88]:
# 3. Now, calculate the average of total_bedrooms again.
df['total_bedrooms'].mean().round(3)

537.871

In [90]:
# 4. Has it changed?

mean_value == df['total_bedrooms'].mean().round(3)

True

Questions 7: Value of the last element of w

In [42]:
df.ocean_proximity.unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [94]:
# 1. Select all the options located on islands.
# 2. Select only columns housing_median_age, total_rooms, total_bedrooms

df.loc[df['ocean_proximity'].isin(['ISLAND']), ['housing_median_age', 'total_rooms', 'total_bedrooms']]

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [95]:
# 3. Get the underlying NumPy array. Let's call it X.
X = np.array(df.loc[df['ocean_proximity'].isin(['ISLAND']), ['housing_median_age', 'total_rooms', 'total_bedrooms']])

In [96]:
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [98]:
# 4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX

X_transpose = X.T
X_transpose

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [99]:
XTX = X_transpose.dot(X)

In [100]:
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [101]:
# 5. Compute the inverse of XTX.
XTX_inverse = np.linalg.inv(XTX)

In [102]:
XTX_inverse

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [104]:
# Checking if dot product is a identity matrix
XTX.dot(XTX_inverse).round(1)

array([[ 1.,  0., -0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

In [106]:
# 6. Create an array y with values [950, 1300, 800, 1000, 1300].
y = [950, 1300, 800, 1000, 1300]

In [107]:
# 7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
XTX_inverse.dot(X_transpose).dot(y)

array([23.12330961, -1.48124183,  5.69922946])

End